### ISSUE TITLE
What is the cutout region for Imagenet

### ISSUE THREAD

**Issue by weiaicunzai** [uoguelph-mlrg/Cutout#4]
Thanks for your work, really great. But I didn't see the experiment on ImageNet, what is the cutout region for ImageNet? Thanks.

**Comment by TDeVries** [comment]
Hello, only ran a few tests on ImageNet, but it seemed like cutout didn't help a while lot. I would recommend trying DropBlock instead, which is effectively cutout applied to the feature maps of the CNN instead of the inputs. There is a nice PyTorch implementation here: https://github.com/miguelvr/dropblock
